services:
  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: 'meuvie'
      MYSQL_USER: 'server'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'strong-password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_database:/var/lib/mysql
  s3-local:
    image: scireum/s3-ninja:latest
    ports:
      - '9444:9000'
    volumes:
      - s3_local_data:/home/sirius/data
volumes:
  mysql_database:
  s3_local_data: